// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechChallengeFIAP.Data.Repositorios;

#nullable disable

namespace TechChallengeFIAP.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250603013535_AddPercentualDescontoAPromocao")]
    partial class AddPercentualDescontoAPromocao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechChallengeFIAP.Domain.Entidades.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassificacaoJogo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DescricaoJogo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<bool>("EhInativo")
                        .HasColumnType("bit");

                    b.Property<string>("NomeJogo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal>("ValorPromocao")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Jogo", (string)null);
                });

            modelBuilder.Entity("TechChallengeFIAP.Domain.Entidades.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("DATETIME2");

                    b.Property<bool>("EhAdministrador")
                        .HasColumnType("BIT");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("BIT");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("UsuarioAtualizador")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("UsuarioCriador")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Pessoa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f4ab7ce-9c51-42b2-86bd-701c9f61ddca"),
                            DataCriacao = new DateTime(2025, 5, 24, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EhAdministrador = true,
                            EhAtivo = true,
                            EmailUsuario = "admin@dominio-exemplo.com",
                            HashSenha = "oTa8GZ7m5lROX1ZZyVlznSTim7oiF8ycUtd++6u0fycaD7jesnyvrNNpzy/A9Pkl",
                            NomeCompleto = "admin",
                            NomeUsuario = "admin",
                            UsuarioAtualizador = "",
                            UsuarioCriador = ""
                        });
                });

            modelBuilder.Entity("TechChallengeFIAP.Domain.Entidades.Promocao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("DATETIME2");

                    b.Property<bool>("EhCancelada")
                        .HasColumnType("BIT");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PercentualDesconto")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.ToTable("Promocao", (string)null);
                });

            modelBuilder.Entity("TechChallengeFIAP.Domain.Entidades.RegistroEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("DadosEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DadosEvento");

                    b.Property<DateTime>("Data")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("Data");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Evento");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PessoaId");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("RegistroEvento", (string)null);
                });

            modelBuilder.Entity("TechChallengeFIAP.Domain.Entidades.Promocao", b =>
                {
                    b.HasOne("TechChallengeFIAP.Domain.Entidades.Jogo", "Jogo")
                        .WithMany("Promocoes")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("TechChallengeFIAP.Domain.Entidades.RegistroEvento", b =>
                {
                    b.HasOne("TechChallengeFIAP.Domain.Entidades.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("TechChallengeFIAP.Domain.Entidades.Jogo", b =>
                {
                    b.Navigation("Promocoes");
                });
#pragma warning restore 612, 618
        }
    }
}
