name: CI/CD - FIAP_TECH_CHALLENGE

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependências
        run: dotnet restore

      - name: Build do projeto
        run: dotnet build --no-restore

      - name: Executar testes
        run: dotnet test --no-build --verbosity normal

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publicar aplicação
        run: dotnet publish -c Release -o ./publish
        
      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fcg65'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
